services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    ports:
      - '3001:3001'
    environment:
      PRODUCER_PORT: 3001
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    ports:
      - '3002:3002'
    environment:
      CONSUMER_PORT: 3002
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
    depends_on:
      rabbitmq:
        condition: service_healthy

  telegram:
    build:
      context: .
      dockerfile: apps/telegram/Dockerfile
    ports:
      - '3003:3003'
    env_file:
      - .env
    environment:
      TELEGRAM_PORT: 3003
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
    depends_on:
      rabbitmq:
        condition: service_healthy
